"""Local library of themes generated by Plymotion.

Lives inside the project checkout (gitignored), separate from the actual
installed system themes under /usr/share/plymouth/themes (that's
installer.py's job). Plymotion is run from the repo and leaves nothing
behind in the user's home. All operations here are unprivileged
filesystem I/O.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from plymotion.core.sorting import natural_sort_key
from plymotion.core.template_generator import WATERMARK_FILENAME

PROJECT_ROOT = Path(__file__).resolve().parents[3]
LIBRARY_DIR = PROJECT_ROOT / "library"
LIBRARY_THEMES_DIR = LIBRARY_DIR / "themes"
MANIFEST_NAME = "theme.json"
PREFS_FILE = LIBRARY_DIR / "prefs.json"


def slugify(name: str) -> str:
    """Turn a display name into a filesystem/ImageDir-safe slug."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", name.strip()).strip("-").lower()
    return slug or "theme"


def unique_slug(name: str) -> str:
    """A slug for `name` guaranteed not to collide with an existing library entry."""
    LIBRARY_THEMES_DIR.mkdir(parents=True, exist_ok=True)
    base = slugify(name)
    slug = base
    n = 2
    while (LIBRARY_THEMES_DIR / slug).exists():
        slug = f"{base}-{n}"
        n += 1
    return slug


@dataclass(frozen=True)
class LibraryTheme:
    slug: str
    name: str
    directory: Path
    frame_count: int
    resolution: tuple[int, int]
    fps: int
    loop_seconds: float
    source_video: str
    created_at: str
    thumbnail: Path | None
    colors: int = 0
    total_bytes: int = 0
    boot_logo: bool = False


_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")


def is_valid_slug(slug: str) -> bool:
    """Whether `slug` is one slugify() could have produced (no path tricks)."""
    return bool(_SLUG_RE.fullmatch(slug))


def save_manifest(theme_dir: Path, **metadata: object) -> None:
    """Write theme.json with arbitrary metadata into an existing theme directory."""
    (theme_dir / MANIFEST_NAME).write_text(json.dumps(metadata, indent=2))


def update_manifest(theme_dir: Path, **changes: object) -> None:
    """Merge `changes` into an existing theme.json."""
    data = json.loads((theme_dir / MANIFEST_NAME).read_text())
    data.update(changes)
    save_manifest(theme_dir, **data)


def sorted_frames(theme_dir: Path) -> list[Path]:
    """All frame*.png in `theme_dir`, in playback order (frame2 before frame10)."""
    return sorted(theme_dir.glob("frame*.png"), key=natural_sort_key)


def _load_theme(theme_dir: Path) -> LibraryTheme | None:
    try:
        data = json.loads((theme_dir / MANIFEST_NAME).read_text())
    except (OSError, json.JSONDecodeError):
        return None

    frames = sorted_frames(theme_dir)
    resolution = data.get("resolution", [0, 0])
    total_bytes = data.get("total_bytes") or sum(f.stat().st_size for f in frames)
    return LibraryTheme(
        slug=theme_dir.name,
        name=data.get("name", theme_dir.name),
        directory=theme_dir,
        frame_count=data.get("frame_count", len(frames)),
        resolution=(int(resolution[0]), int(resolution[1])),
        fps=data.get("fps", 0),
        loop_seconds=data.get("loop_seconds", 0.0),
        source_video=data.get("source_video", ""),
        created_at=data.get("created_at", ""),
        thumbnail=frames[0] if frames else None,
        colors=data.get("colors", 0),
        total_bytes=int(total_bytes),
        boot_logo=(theme_dir / WATERMARK_FILENAME).is_file(),
    )


def list_library_themes() -> list[LibraryTheme]:
    """List all themes saved to the local library. Corrupt entries are skipped."""
    if not LIBRARY_THEMES_DIR.is_dir():
        return []

    themes = []
    for manifest_path in sorted(LIBRARY_THEMES_DIR.glob(f"*/{MANIFEST_NAME}")):
        theme = _load_theme(manifest_path.parent)
        if theme is not None:
            themes.append(theme)
    return themes


def get_library_theme(slug: str) -> LibraryTheme | None:
    """One library theme by slug, or None if it doesn't exist or is corrupt."""
    if not is_valid_slug(slug):
        return None
    return _load_theme(LIBRARY_THEMES_DIR / slug)


def delete_library_theme(slug: str) -> None:
    """Remove a theme from the local library. Unprivileged; this is our own data."""
    if not is_valid_slug(slug):
        raise ValueError(f"Invalid theme slug: {slug!r}")
    theme_dir = LIBRARY_THEMES_DIR / slug
    if theme_dir.is_dir():
        shutil.rmtree(theme_dir)


def sample_preview_frames(theme_dir: Path, max_frames: int = 24) -> list[Path]:
    """Frames in playback order, uniformly sampled down to at most `max_frames`.

    Used for lightweight animated gallery previews: showing every frame of a
    long animation would be slow to load and unnecessary for a preview.
    """
    frames = sorted_frames(theme_dir)
    if len(frames) <= max_frames or not frames:
        return frames
    step = len(frames) / max_frames
    return [frames[int(i * step)] for i in range(max_frames)]


def load_prefs() -> dict[str, object]:
    """Small persisted UI preferences (currently just theme_mode). Best-effort."""
    try:
        return json.loads(PREFS_FILE.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def save_prefs(**prefs: object) -> None:
    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    PREFS_FILE.write_text(json.dumps(prefs, indent=2))


def update_prefs(**changes: object) -> dict[str, object]:
    """Merge `changes` into the stored preferences and return the result."""
    prefs = load_prefs()
    prefs.update(changes)
    save_prefs(**prefs)
    return prefs

