"""Local library of themes generated by Plymotion.

Lives inside the project checkout (gitignored), separate from the actual
installed system themes under /usr/share/plymouth/themes (that's
installer.py's job). All operations here are unprivileged filesystem I/O.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

from plymotion.sorting import natural_sort_key

PROJECT_ROOT = Path(__file__).resolve().parents[2]
LIBRARY_DIR = PROJECT_ROOT / "library"
LIBRARY_THEMES_DIR = LIBRARY_DIR / "themes"
MANIFEST_NAME = "theme.json"
PREFS_FILE = LIBRARY_DIR / "prefs.json"


def slugify(name: str) -> str:
    """Turn a display name into a filesystem/ImageDir-safe slug."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", name.strip()).strip("-").lower()
    return slug or "theme"


def unique_slug(name: str) -> str:
    """A slug for `name` guaranteed not to collide with an existing library entry."""
    LIBRARY_THEMES_DIR.mkdir(parents=True, exist_ok=True)
    base = slugify(name)
    slug = base
    n = 2
    while (LIBRARY_THEMES_DIR / slug).exists():
        slug = f"{base}-{n}"
        n += 1
    return slug


@dataclass(frozen=True)
class LibraryTheme:
    slug: str
    name: str
    directory: Path
    frame_count: int
    resolution: tuple[int, int]
    fps: int
    loop_seconds: float
    source_video: str
    created_at: str
    thumbnail: Path | None


def save_manifest(theme_dir: Path, **metadata: object) -> None:
    """Write theme.json with arbitrary metadata into an existing theme directory."""
    (theme_dir / MANIFEST_NAME).write_text(json.dumps(metadata, indent=2))


def _sorted_frames(theme_dir: Path) -> list[Path]:
    return sorted(theme_dir.glob("frame*.png"), key=natural_sort_key)


def list_library_themes() -> list[LibraryTheme]:
    """List all themes saved to the local library. Corrupt entries are skipped."""
    if not LIBRARY_THEMES_DIR.is_dir():
        return []

    themes = []
    for manifest_path in sorted(LIBRARY_THEMES_DIR.glob(f"*/{MANIFEST_NAME}")):
        try:
            data = json.loads(manifest_path.read_text())
        except (OSError, json.JSONDecodeError):
            continue

        theme_dir = manifest_path.parent
        frames = _sorted_frames(theme_dir)
        resolution = data.get("resolution", [0, 0])
        themes.append(
            LibraryTheme(
                slug=theme_dir.name,
                name=data.get("name", theme_dir.name),
                directory=theme_dir,
                frame_count=data.get("frame_count", len(frames)),
                resolution=(int(resolution[0]), int(resolution[1])),
                fps=data.get("fps", 0),
                loop_seconds=data.get("loop_seconds", 0.0),
                source_video=data.get("source_video", ""),
                created_at=data.get("created_at", ""),
                thumbnail=frames[0] if frames else None,
            )
        )
    return themes


def delete_library_theme(slug: str) -> None:
    """Remove a theme from the local library. Unprivileged; this is our own data."""
    theme_dir = LIBRARY_THEMES_DIR / slug
    if theme_dir.is_dir():
        shutil.rmtree(theme_dir)


def sample_preview_frames(theme_dir: Path, max_frames: int = 24) -> list[Path]:
    """Frames in playback order, uniformly sampled down to at most `max_frames`.

    Used for lightweight animated gallery previews: showing every frame of a
    long animation would be slow to load and unnecessary for a preview.
    """
    frames = _sorted_frames(theme_dir)
    if len(frames) <= max_frames or not frames:
        return frames
    step = len(frames) / max_frames
    return [frames[int(i * step)] for i in range(max_frames)]


def load_prefs() -> dict[str, object]:
    """Small persisted UI preferences (currently just theme_mode). Best-effort."""
    try:
        return json.loads(PREFS_FILE.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def save_prefs(**prefs: object) -> None:
    LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    PREFS_FILE.write_text(json.dumps(prefs, indent=2))
