"""Generate Plymouth .script and .plymouth files from templates."""

from __future__ import annotations

from pathlib import Path
from string import Template

# Plymouth's `script` module calls the refresh callback at a fixed rate
# (Plymouth.SetRefreshRate), 50 Hz by default, independent of the fps used
# to extract frames from the source video. Our generated script advances
# exactly one frame per callback, so on-screen playback speed is
# frame_count / PLYMOUTH_DEFAULT_REFRESH_RATE, not the extraction fps.
PLYMOUTH_DEFAULT_REFRESH_RATE = 50

SCRIPT_TEMPLATE = Template("""\
for(i = 0; i < $frame_count; i++)
  video_image_arr[i] = Image("$image_dir/frame" + (i + 1) + ".png");

pos_x = Window.GetWidth()/2 - video_image_arr[0].GetWidth()/2;
pos_y = Window.GetHeight()/2 - video_image_arr[0].GetHeight()/2;

sprite = Sprite(video_image_arr[0]);
sprite.SetX(pos_x);
sprite.SetY(pos_y);
sprite.SetZ(15);

count = 0;

fun refresh_callback () {
  sprite.SetImage(video_image_arr[count]);
  sprite.SetOpacity(1);
  count++;
  if (count >= $frame_count) {
    count = 0;
  }
}

Plymouth.SetRefreshFunction(refresh_callback);
""")

PLYMOUTH_TEMPLATE = Template("""\
[Plymouth Theme]
Name=$theme_name
Description=Generated by Plymotion - video boot splash
ModuleName=script

[script]
ImageDir=$image_dir
ScriptFile=$script_file
""")


def generate_script(output_path: Path, frame_count: int, image_dir: str) -> None:
    """Write the .script file with looping support."""
    content = SCRIPT_TEMPLATE.substitute(
        frame_count=frame_count,
        image_dir=image_dir,
    )
    output_path.write_text(content)


def estimate_loop_seconds(
    frame_count: int, refresh_rate: int = PLYMOUTH_DEFAULT_REFRESH_RATE
) -> float:
    """Seconds a single loop of the generated animation takes on-screen.

    Not tied to the extraction fps or the source video's duration: Plymouth
    replays frames at its own fixed refresh rate.
    """
    if refresh_rate <= 0:
        raise ValueError("refresh_rate must be positive")
    return frame_count / refresh_rate


def generate_plymouth(
    output_path: Path,
    theme_name: str,
    image_dir: str,
    script_file: str,
) -> None:
    """Write the .plymouth theme config."""
    content = PLYMOUTH_TEMPLATE.substitute(
        theme_name=theme_name,
        image_dir=image_dir,
        script_file=script_file,
    )
    output_path.write_text(content)
